pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview5-011568

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c Release -o build'
    zipAfterPublish: false
    modifyOutputPath: false
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/WhiteUnitySpa/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'White-Unity-Spa'
    publishLocation: 'Container'