pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview5-011568

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c Release -o build'
    zipAfterPublish: false
    modifyOutputPath: false
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'build/WhiteUnitySpa/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/spa.zip'
    replaceExistingArchive: true